[tool.poetry]
name = "mg_exporter"
version = "0.2.3"
description = "Prometheus exporter for Memgraph. Supports standalone and HA mode."
authors = ["Josip Mrden <josip.mrden@memgraph.io>", "Andi Skrgat <andi.skrgat@memgraph.io>"]

[tool.poetry.dependencies]
python = "^3.9.0"
prometheus-client = "^0.21.1"
requests = "^2.32.3"
PyYAML = "^6.0.1"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
flake8 = "^6.0.0"
pre-commit = "^3.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
