exporter:
  port: 9115
  pull_frequency_seconds: 25
instances:
  - name: coord1
    url: http://127.0.0.1
    port: 9091
  - name: coord2
    url: http://127.0.0.1
    port: 9092
  - name: coord3
    url: http://127.0.0.1
    port: 9093
  - name: data1
    url: http://127.0.0.1
    port: 9094
  - name: data2
    url: http://127.0.0.1
    port: 9095
