from prometheus_client import Gauge


_data = [
    "AccumulateOperator",
    "AggregateOperator",
    "ApplyOperator",
    "CallProcedureOperator",
    "CartesianOperator",
    "ConstructNamedPathOperator",
    "CreateExpandOperator",
    "CreateNodeOperator",
    "DeleteOperator",
    "DistinctOperator",
    "EdgeUniquenessFilterOperator",
    "EmptyResultOperator",
    "EvaluatePatternFilterOperator",
    "ExpandOperator",
    "ExpandVariableOperator",
    "FilterOperator",
    "ForeachOperator",
    "HashJoinOperator",
    "IndexedJoinOperator",
    "LimitOperator",
    "MergeOperator",
    "OnceOperator",
    "OptionalOperator",
    "OrderByOperator",
    "PeriodicCommitOperator",
    "PeriodicSubqueryOperator",
    "ProduceOperator",
    "RemoveLabelsOperator",
    "RemovePropertyOperator",
    "RollUpApplyOperator",
    "ScanAllByEdgeIdOperator",
    "ScanAllByEdgeOperator",
    "ScanAllByEdgeTypeOperator",
    "ScanAllByEdgeTypePropertyOperator",
    "ScanAllByEdgeTypePropertyRangeOperator",
    "ScanAllByEdgeTypePropertyValueOperator",
    "ScanAllByIdOperator",
    "ScanAllByLabelOperator",
    "ScanAllByLabelPropertyOperator",
    "ScanAllByLabelPropertyRangeOperator",
    "ScanAllByLabelPropertyValueOperator",
    "ScanAllByPointDistanceOperator",
    "ScanAllByPointWithinbboxOperator",
    "ScanAllOperator",
    "SetLabelsOperator",
    "SetPropertiesOperator",
    "SetPropertyOperator",
    "SkipOperator",
    "UnionOperator",
    "UnwindOperator",
]


PrometheusOperatorData = {name: Gauge(name, f"Number of times {name} has been called.", ["instance_name"]) for name in _data}
